copyright = "© Marcus Nunes"
defaultContentLanguage = "en"
disableKinds = ["term"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Fortaleza"
timeout = "120s"
title = "Portfólio"

[params]
  defaultTheme = "dark"
  description = "Portfolio fotográfico de Marcus Nunes - marcusnunes.me"
  title = "Portfolio"
  [params.author]
    email = "marcus.nunes@gmail.com"
    name = "Marcus Nunes"
  [params.socialIcons]
    instagram = "https://www.instagram.com/grandeabobora"
    email = "mailto:marcus.nunes@gmail.com"
    website = "https://marcusnunes.me"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3

[services]
  [services.rss]
    limit = 100


[related]
  includeNewer = true
  threshold = 10
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 50



